[View in Colaboratory](https://colab.research.google.com/github/sabumjung/Tensorflow/blob/master/%EC%95%88%EB%85%95%ED%95%98%EC%84%B8%EC%9A%94,_Colaboratory%EC%9E%85%EB%8B%88%EB%8B%A4.ipynb)

## 강화학습 아서줄리아니 1번
03_01_TF_RL_Q-Table_Algorithm.ipynb

In [2]:
!pip install gym

    100% |████████████████████████████████| 1.5MB 11.9MB/s 
    100% |████████████████████████████████| 1.0MB 13.6MB/s 
  Running setup.py bdist_wheel for gym ... - \ | / done
  Stored in directory: /content/.cache/pip/wheels/cb/14/71/f4ab006b1e6ff75c2b54985c2f98d0644fffe9c1dddc670925
Successfully built gym


In [0]:
import gym
import numpy as np

In [0]:
env = gym.make('FrozenLake-v0')

In [5]:
#Initialize table with all zeros
#16개의 상태에 대한 Value값 테이블 : 16*4로 구성된 0값 행렬
Q = np.zeros([env.observation_space.n,env.action_space.n])
print(Q)

#hyper parameter 설정
lr = .8
y = .95
num_episodes = 2000
#총 리워드와 매 에피소드별 단계를 저장하기 위한 리스트 생성
#jList = []
rList = []
for i in range(num_episodes):
    #환경 재설정
    #첫번째 신규 관측값을 가져오기
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    
    #Q테이블 학습 알고리즘-----------------------
    while j < 99:
        j+=1
        #Q테이블로부터 그리디 정책(argmax)에 의해 action 선택하기(with noise가 있음)
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #환경으로부터 신규 state와 reward를 가져오기
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.5395


In [7]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[8.11467355e-02 1.76269749e-02 1.54313272e-02 1.22763516e-02]
 [8.97811753e-05 1.06597312e-03 0.00000000e+00 1.09156027e-01]
 [6.15995074e-03 6.90392408e-03 7.91624863e-03 1.15336411e-01]
 [1.00737517e-03 2.50650154e-03 2.08758643e-04 5.27065114e-02]
 [1.77747897e-01 2.88662261e-03 8.07653689e-03 8.22011668e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.91917813e-04 4.96210271e-04 8.25614313e-04 1.36826136e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.72826035e-03 5.87877849e-03 1.79544696e-01]
 [0.00000000e+00 7.62710372e-02 2.04825295e-03 2.62877309e-03]
 [1.36300887e-02 9.40703209e-04 0.00000000e+00 1.38133980e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.18179260e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.81116900e-01]
 [0.00000000e+00 0.00000000e+00 0.

In [8]:
import numpy as np
def one_hot_encode(x, n_classes):
    return np.eye(n_classes)[x]

def main():
    list=[0,1,2,3,4,3,2,1,0]
    print(list)
    n_classes=5
    one_hot_list=one_hot_encode(list, n_classes)
    print(one_hot_list)
    list=[3]
    print(one_hot_encode(list,8))
if __name__=="__main__":
    main()
    
list=[1]
a=one_hot_encode(list,16)
print("State(t)=", a)
print("Next Action(t+1)=",np.matmul(a,Q))   

[0, 1, 2, 3, 4, 3, 2, 1, 0]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[0. 0. 0. 1. 0. 0. 0. 0.]]
State(t)= [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Next Action(t+1)= [[8.97811753e-05 1.06597312e-03 0.00000000e+00 1.09156027e-01]]
