[View in Colaboratory](https://colab.research.google.com/github/sabumjung/Tensorflow/blob/master/2%EC%9E%A5.ipynb)

In [1]:
import tensorflow as tf
print(tf.__version__)

1.10.0


In [3]:
import tensorflow as tf
with tf.Session() as session:
    x = tf.placeholder(tf.float32,[1],name="x")
    y = tf.placeholder(tf.float32,[1],name="y")
    z = tf.constant(2.0)
    y = x * z
    x_in = [100]
    y_output = session.run(y,{x:x_in})
    print(y_output)

[200.]


In [4]:
import tensorflow as tf

scalar = tf.constant(100)
vector = tf.constant([1,2,3,4,5])
matrix = tf.constant([[1,2,3],[4,5,6]])
cube_matrix = tf.constant([[[1],[2],[3]],[[4],[5],[6]],[[7],[8],[9]]])


print(scalar.get_shape())
print(vector.get_shape())
print(matrix.get_shape())
print(cube_matrix.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


In [6]:
import tensorflow as tf
import numpy as np

#tensore 1d con valori costanti
tensor_1d = np.array([1,2,3,4,5,6,7,8,9,10])
tensor_1d = tf.constant(tensor_1d)
with tf.Session() as sess:
    print (tensor_1d.get_shape())
    print sess.run(tensor_1d)

(10,)
[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
import tensorflow as tf
import numpy as np

#tensore 2d con valori variabili
tensor_2d = np.array([(1,2,3),(4,5,6),(7,8,9)])
tensor_2d = tf.Variable(tensor_2d)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print (tensor_2d.get_shape())
    print sess.run(tensor_2d)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
import tensorflow as tf
import numpy as np

interactive_session = tf.InteractiveSession()
tensor = np.array([1, 2, 3, 4, 5])
tensor = tf.constant(tensor)
print(tensor.eval())
interactive_session.close()

[1 2 3 4 5]


In [9]:
import tensorflow as tf
import numpy as np
tensor_3d = np.array([[[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8]],
                      [[ 9, 10, 11],[12, 13, 14],[15, 16, 17]],
                      [[18, 19, 20],[21, 22, 23],[24, 25, 26]]])

tensor_3d = tf.convert_to_tensor(tensor_3d, dtype=tf.float64)
with tf.Session() as sess:
    print (tensor_3d.get_shape())
    print sess.run(tensor_3d)

(3, 3, 3)
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]]


In [18]:
import tensorflow as tf

value = tf.Variable(0, name="value")
one = tf.constant(1)
new_value = tf.add(value,one)
update_value=tf.assign(value,new_value)

initialize_var = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(initialize_var)
    print(sess.run(value))
    for _ in range(10):
        sess.run(update_value)
        print(sess.run(value))

0
1
2
3
4
5
6
7
8
9
10


In [19]:
import tensorflow as tf

constant_A = tf.constant([100.0])
constant_B = tf.constant([300.0])
constant_C = tf.constant([3.0])

sum_ = tf.add(constant_A, constant_B)
mul_ = tf.multiply(constant_A, constant_C)

with tf.Session() as sess:
  result = sess.run([sum_, mul_])
  print(result)

[array([400.], dtype=float32), array([300.], dtype=float32)]


In [20]:
import tensorflow as tf
import numpy as np

a = 3
b = 2

x = tf.placeholder(tf.float32, shape=(a, b))
y = tf.add(x, x)

data = np.random.rand(a, b)
sess = tf.Session()
print(sess.run(y,feed_dict={x: data}))

[[1.7597444  1.368224  ]
 [0.56452113 0.74353635]
 [0.53508675 1.0511423 ]]


In [0]:
import tensorflow as tf

weight = tf.Variable(1.0, name="weight")
input_value = tf.constant(0.5, name="input_value")
expected_output = tf.constant(0.0, name="expected_output")
model = tf.multiply(input_value,weight, "model")
loss_function = tf.pow(expected_output - model, 2, name="loss_function")

optimizer = tf.train.GradientDescentOptimizer(0.025).minimize(loss_function)

for value in [input_value, weight, expected_output, model, loss_function]:
	tf.summary.scalar(value.op.name, value)

summaries = tf.summary.merge_all()
sess = tf.Session()

summary_writer = tf.summary.FileWriter('log_simple_stats', sess.graph)

sess.run(tf.global_variables_initializer())

for i in range(100):
	summary_writer.add_summary(sess.run(summaries), i)
	sess.run(optimizer)