[View in Colaboratory](https://colab.research.google.com/github/sabumjung/Tensorflow/blob/master/DL_w_TF_2%EC%9E%A5.ipynb)

In [2]:
import tensorflow as tf
tf.__version__

'1.10.0-rc1'

In [4]:
import tensorflow as tf
with tf.Session() as session:
  x=tf.placeholder(tf.float32,[1],name="x")
  y=tf.placeholder(tf.float32,[1],name="y")
  z=tf.constant(2.0)
  y=x*z
  x_in=[1]
  y_output=session.run(y,{x:x_in})
  print(y_output)

[2.]


In [1]:
import tensorflow as tf
scalar = tf.constant(100)
vector = tf.constant([1, 2, 3, 4, 5])
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
cube_matrix = tf.constant([[[1], [2], [3]], [[4], [5], [6]], [[7], [8], [9]]])
print(scalar.get_shape())
print(vector.get_shape())
print(matrix.get_shape())
print(cube_matrix.get_shape())

()
(5,)
(2, 3)
(3, 3, 1)


In [8]:
import tensorflow as tf
import numpy as np

tensor_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tensor_1d = tf.constant(tensor_1d)
with tf.Session() as sess:
  print(tensor_1d.get_shape())
  print(sess.run(tensor_1d))


(10,)
[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
import tensorflow as tf
import numpy as np

tensor_2d = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
tensor_2d = tf.Variable(tensor_2d)
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  print(tensor_2d.get_shape())
  print(sess.run(tensor_2d))

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
import tensorflow as tf
import numpy as np

interactive_session = tf.InteractiveSession()
tensor = np.array([1, 2, 3, 4, 5])
tensor = tf.constant(tensor)
print(tensor.eval())
interactive_session.close()

[1 2 3 4 5]


In [11]:
import tensorflow as tf
import numpy as np

tensor_3d = np.array([[[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8]],
  [[ 9, 10, 11],[12, 13, 14],[15, 16, 17]],
  [[18, 19, 20],[21, 22, 23],[24, 25, 26]]])

tensor_3d = tf.convert_to_tensor(tensor_3d, dtype=tf.float64)
with tf.Session() as sess:
  print(tensor_3d.get_shape())
  print(sess.run(tensor_3d))

(3, 3, 3)
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]]


In [12]:
import tensorflow as tf

#변수는 tf.Variable()명령문을 이용한다.
#스칼라값 0으로 초기화한 변수 value를 만든다.
value = tf.Variable(0, name="value")
#상수1을 선언한다.
one = tf.constant(1)
#add, assign은 계산그래프의 노드일뿐, 세션실행전까지 실제값을 할당하지는 않는다.
new_value = tf.add(value, one)
update_value = tf.assign(value, new_value)

initialize_var = tf.global_variables_initializer()

#계산그래프를 초기화한다.
with tf.Session() as sess:
  sess.run(initialize_var)
  print(sess.run(value))
  for _ in range(10):
    sess.run(update_value)
    print(sess.run(value))

0
1
2
3
4
5
6
7
8
9
10


In [13]:
#연산결과를 가져오려면 
#1) session객체에서 run()함수를 호출
#2) 그래프를 실행
#3) 해당텐서를 전달

#여러개의 텐서를 가져올 수 있음
import tensorflow as tf

constant_A = tf.constant([100.0])
constant_B = tf.constant([300.0])
constant_C = tf.constant([3.0])

sum_ = tf.add(constant_A, constant_B)
mul_ = tf.multiply(constant_A, constant_C)

with tf.Session() as sess:
  #sum_, mul_텐서를 불러온다.
  #텐서값을 생성하는데 필요한 연산은 한번만 실행됨
  #텐서별로 한번이 아님(아래 연산은 한번만 실행, 두번이 아님)
  result = sess.run([sum_, mul_])
  print(result)

[array([400.], dtype=float32), array([300.], dtype=float32)]


In [21]:
import tensorflow as tf
import numpy as np

a = 3
b = 2

#3행2열로 구성된 x데이터
x = tf.placeholder(tf.float32, shape=(a, b))
#x+x연산을 수행함
y = tf.add(x, 1)

data = np.random.rand(a, b)
sess = tf.Session()
print(sess.run(y,feed_dict={x: data}))

[[1.7342111 1.2913954]
 [1.2864573 1.5373712]
 [1.1651804 1.4495637]]
